In [1]:
import numpy as np

In [5]:
#1D array
a = np.array([1,2,3,4,5])
print(a)
print("Shape:",a.shape)

[1 2 3 4 5]
Shape: (5,)


In [7]:
#2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("Shape:",b.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [10]:
#Indexing
print(a[0])
print(b[1,2])

1
6


In [14]:
#Slicing
print(a[1:4])
print(b[:,2])

[2 3 4]
[3 6]


In [24]:
#Broadcasting
c = a+5
print(c)
print(b+5)

[ 6  7  8  9 10]
[[ 6  7  8]
 [ 9 10 11]]


In [31]:
##Practice Tasks##
#!.Create a 3*3 Numpy array
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
#2.print first row and last column
print("First row:",d[0])
print("Last column:",d[:,2])
#Add 5 to all elements using broadcasting
print(d+5)

First row: [1 2 3]
Last column: [3 6 9]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [33]:
###MINI TASK###
marks = np.array([65,70,80,90,45])
print(marks+5)              #increasing all marks by 5
print(marks.mean())         #Find avarage marks
print(marks.max())          #highest marks

[70 75 85 95 50]
70.0
90
