In [2]:
import numpy as np

In [4]:
#Create array
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
#Reshaped array
b= a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#Flatten
print("Flatten:",a.flatten())

Flatten: [1 2 3 4 5 6]


In [9]:
#ravel 
c = a.ravel()
c[0] = 99
print(a)

[[99  2  3]
 [ 4  5  6]]


In [15]:
#Boolean masking
arr = np.array([10,3,7,2,15])
mask = arr>5                                  #mask can caonvert that condition true that elements is  othre wise false
print("Greater than 5:",arr[arr>5])
print("Greater than 5 :",mask)


Greater than 5: [10  7 15]
Greater than 5 : [ True False  True False  True]


In [17]:
#Statistics
marks = np.array([[70,40,50],[79,39,50]])
print("Average marks:",marks.mean())
print("Row wise mean:",marks.mean(axis=1))
print("Column wise mean:",marks.mean(axis=0))

Average marks: 54.666666666666664
Row wise mean: [53.33333333 56.        ]
Column wise mean: [74.5 39.5 50. ]


In [20]:
##Pratice Task##
score = np.array([[3,8,6],[4,7,9],[2,18,6],[4,7,3]])
#reshape
print("Reshaped array:",score.reshape(3,4))
#Replace all values >5 with 0
score[score>5] = 0
print(score)
#Finding Max of row and Min of column
print("Max of row is:",score.max(axis=1))
print("Min of column is:",score.min(axis=0))

Reshaped array: [[ 3  8  6  4]
 [ 7  9  2 18]
 [ 6  4  7  3]]
[[3 0 0]
 [4 0 0]
 [2 0 0]
 [4 0 3]]
Max of row is: [3 4 2 4]
Min of column is: [2 0 0]
